version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod.simple
    image: bella-voice-app:latest
    container_name: bella-app-prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgresql+asyncpg://bella_user:${POSTGRES_PASSWORD:-BellaPassword123}@db:5432/bella_db
      - REDIS_URL=redis://redis:6379/0
      - TWILIO_WEBHOOK_URL=http://15.157.56.64/twilio/voice
      - PRODUCTION_BASE_URL=http://15.157.56.64
      - TZ=America/Winnipeg
      # All other environment variables from .env.prod
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - bella-network

  db:
    image: postgres:15-alpine
    container_name: bella-db-prod
    environment:
      POSTGRES_DB: bella_db
      POSTGRES_USER: bella_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-BellaPassword123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bella_user -d bella_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bella-network

  redis:
    image: redis:7-alpine
    container_name: bella-redis-prod
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bella-network

  nginx:
    image: nginx:alpine
    container_name: bella-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.simple.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - bella-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  bella-network:
    driver: bridge