"""add appointments table

Revision ID: 28f57de3f2bb
Revises: 5180da4d0594
Create Date: 2025-08-27 17:17:16.464863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f57de3f2bb'
down_revision: Union[str, Sequence[str], None] = '5180da4d0594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), server_default='30', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='booked', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'starts_at', name='uq_appointments_user_id_starts_at')
    )
    op.create_index('ix_appointments_starts_at', 'appointments', ['starts_at'], unique=False)
    op.create_index('ix_appointments_user_id', 'appointments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_user_id', table_name='appointments')
    op.drop_index('ix_appointments_starts_at', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
