"""drop users.date

Revision ID: b4894a8d2bc1
Revises: 28f57de3f2bb
Create Date: 2025-08-27 17:46:00.713865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4894a8d2bc1'
down_revision: Union[str, Sequence[str], None] = '28f57de3f2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
